import { Link } from "react-router"
import Header from "../components/header"
import "./styles/scopeThree.css"
import scope3Infographic from "../assets/diagrams/Scope_3_infographic.webp";

export default function ScopeThreePage () {
    return (
        <main className="scope-three">
            <Header />

            <Link to="/" className="back-link">
                Back
            </Link>

            <section className="hero">
                <h1>Scope 3 Emissions</h1>
            </section>

            <section className="content-grid">
                <article className="info-card">
                    Scope 3 emissions include all emissions, both upstream and downstream, 
                    that contribute to your carvon footprint.<br/>
                    These can include anything from transportation emissions from cars and trucks, 
                    through to the emissions produced <br/>
                    during goods manufacturing, and even the green waste that 
                    ends up in landfill<br/>
                    <figure className="infographic">
                        <img 
                        src={ scope3Infographic }
                        alt="An infographic on scope 3 emissions"
                        />
                        <figcaption>
                            An infographic showing the contributors to scope 3 emissions.
                            https://www.csl.com/we-are-csl/vita-original-stories/2023/explainer-what-are-scope-3-emissions-targets
                        </figcaption>
                    </figure>
                    In a business context scope 3 emissions are one of the hardest contributors to total emissions to track.<br/>
                    This is due to a number of reasons including:<br/>
                    <ul>
                        <li>
                            Size: A business may have hundreds of suppliers to track and maintain accurate records<br/>
                            of their activities.
                        </li>
                        <li>
                            Variability: Suppliers will range across a variety of different industries, and all use<br/>
                            a variety of different materials, equipment, and vehicles all of which have different<br/>
                            emission factors (EF) associated with them.
                        </li>
                        <li>
                            Accuracy: The data being provided is the burden of the supplier, meaning they are required<br/>
                            to report emission contributing factors and activities, some of which isn't always 100%<br/>
                            accurate.
                        </li>
                        <li>
                            Confidentiality: Some suppliers don't want to share the specifics of their work with their<br/>
                            clients. This can lead to the submission of false or misleading details, not maliciously,<br/>
                            but purely because suppliers don't want to share specific material or equipment specifications<br/>
                            with their clients.
                        </li>
                        <li>
                            Reduction: Standardised methods for calculating scope 3 emissions don't account any reduction<br/>
                            techniques that suppliers have already implemented. This causes miscalculation in the<br/>
                            observed emissions and doesn't reward suppliers for measures taken for working towards net zero.
                        </li>
                    </ul>
                    By finding an accurate method to calculate the scope 3 emissions generated by suppliers a business<br/>
                    may better determine their total carbon footprint and work more diligently to achieving net zero.
                </article>
            </section>
            <nav className="page-nav" aria-label="Page navigation">
                <Link to="/" className="page-nav-link page-nav-link-left">
                    Back
                </Link>
                <Link to="/solution" className="page-nav-link page-nav-link-right">
                    Solution
                </Link>
            </nav>
        </main>
    );
}
